export enum Amenities {
  WI_FI = 'wifi',
  RESTAURANT = 'restaurant',
  ROOM_SERVICE = 'room_service',
  MEETING_ROOM = 'meeting_room',
  LAUNDRY = 'local_laundry_service',
  BREAKFAST = 'bakery_dining',
  PARKING = 'local_parking',
  FITNESS_CENTER = 'fitness_center',
  POOL = 'pool',
  SPA = 'spa',
  STEAM_ROOM = 'hot_tub',
  PETS = 'pets',
  PUB = 'sports_bar',
  AIR_CONDITIONING = 'ac_unit',
  SAFE = 'lock',
}
